services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - nats
      - clickhouse
    environment:
      PORT: 8080
      POSTGRES_DSN: postgres://user:password@postgres:5432/goodsdb?sslmode=disable
      REDIS_ADDR: redis:6379
      NATS_URL: nats://nats:4222
      MIGRATION_FILE: migrations.sql

  log-consumer:
    build:
      context: .
      dockerfile: log-consumer.dockerfile
    depends_on:
      - nats
      - clickhouse
    environment:
      NATS_URL: nats://nats:4222
      CLICKHOUSE_ADDR: clickhouse:9000
    restart: on-failure


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goodsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10
    restart: unless-stopped
    ports:
      - "4222:4222"  
      - "8222:8222" 
    command: >
      -js
    volumes:
      - nats-data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  pgdata:
  clickhouse-data:
  nats-data:
